##### Pandas
Pandas es una librería de Python cuyo nombre deriva del término panel data (utilizado para referirse a conjuntos de datos estructurados multidimensionales). Proporciona estructuras de datos y funciones de alto nivel que permiten manipular y analizar datos estructurados de manera cómoda y eficiente.
Estructuras de datos principales:
- Serie (Series): Estructura unidimensional que contiene un arreglo de datos y un conjunto de etiquetas asociado llamado índice (index).
- DataFrame: Estructura tabular bidimensional orientada a columnas, con etiquetas organizadas en ejes verticales (filas/eje 0) y horizontales (columnas/eje 1).

---
Series

In [4]:
# Importar libreria Pandas
import pandas as pd

# Construir una serie de Pandas a partir de una lista
datos = [100, 200, 300, 400, 500]
series= pd.Series(datos)

print(f'Series: \n{series}')

datos1 = [100, 200, 300.1, 400, 500]
series1= pd.Series(datos1)
print(f'\nSeries1: \n{series1}')


print(f'\nEl primer elemento de la serie es: {series[0]}')

Series:
0    100
1    200
2    300
3    400
4    500
dtype: int64

Series1:
0    100.0
1    200.0
2    300.1
3    400.0
4    500.0
dtype: float64

El primer elemento de la serie es: 100

In [5]:
# Construir una serie de Pandas con una lista de índices personalizados
series_datos = pd.Series(datos, index=['sensor1', 'sensor2', 'sensor3', 'sensor4', 'sensor5'])
print(series_datos)

sensor1    100
sensor2    200
sensor3    300
sensor4    400
sensor5    500
dtype: int64

In [6]:
# Creacion de una serie de Pandas a partir de un diccionario
produccion = {
    'Dia 1': 1000,
    'Dia 2': 2100,
    'Dia 3': 1500,
    'Dia 4': 1300,
    'Dia 5': 9000,
}

series_prod = pd.Series(produccion)
print(series_prod)

Dia 1    1000
Dia 2    2100
Dia 3    1500
Dia 4    1300
Dia 5    9000
dtype: int64

--- 
Acceder a elemenos de una serie
```
NombreSerie[index]

NombreSerie.loc[etiqueta]

NombreSerie.iloc[posicion]
```

In [7]:
# Imprimir Serie de Pandas
print(series_prod)

# Acceder a un elemento de la serie de datos por su índice
print(f'\nEl primer elemento de la serie de datos es: {series_prod.iloc[0]}')

# Acceder a un elemento de la serie de datos por su etiqueta
print(f"\nDia 1: {series_prod['Dia 1']}")

Dia 1    1000
Dia 2    2100
Dia 3    1500
Dia 4    1300
Dia 5    9000
dtype: int64

El primer elemento de la serie de datos es: 1000

Dia 1: 1000

In [8]:
# Acceder a un elemento de la serie por su índice
print(f"\nIndice: {series_datos['sensor1']}")

# Loc: Usa los nombres de las filas o columnas en lugar de su posición numérica entera.
print(f"Loc: {series_datos.loc['sensor1']}")

# iloc: Usa la indexación por posición numérica entera.
print(f'Iloc: {series_datos.iloc[0]}')

Indice: 100
Loc: 100
Iloc: 100

---
Remplazar indices, agregar elementos

In [9]:
# Remplazar los índices de la serie por otros personalizados
series_datos = pd.Series(datos, index=['ap1', 'ap2', 'ap3', 'ap4', 'ap5'])

print(series_datos)

print(series_datos.loc['ap1'])
print(series_datos.iloc[2])

ap1    100
ap2    200
ap3    300
ap4    400
ap5    500
dtype: int64
100
300

In [10]:
# Agregar un nuevo elemento a la serie
series_datos['ap6'] = 600

# Imprimir la serie modificada
print('\nSerie Modificada: ')
print(series_datos)

Serie Modificada:
ap1    100
ap2    200
ap3    300
ap4    400
ap5    500
ap6    600
dtype: int64

In [11]:
# Filtrar elementos de la serie que cumplan una condición
print('\nSerie datos: ')
print(series_datos)

# Remplazar los índices de la serie por otros personalizados
series_datos.index = ['sensor1', 'sensor2', 'sensor3', 'sensor4', 'sensor5', 'sensor6']
print(series_datos)

# Imprimir los elementos de la serie que sean mayores a 300
print('\nElementos mayores a 300:')
print(series_datos[series_datos > 300])

Serie datos:
ap1    100
ap2    200
ap3    300
ap4    400
ap5    500
ap6    600
dtype: int64
sensor1    100
sensor2    200
sensor3    300
sensor4    400
sensor5    500
sensor6    600
dtype: int64

Elementos mayores a 300:
sensor4    400
sensor5    500
sensor6    600
dtype: int64

---
Atributos

In [12]:
print(f'Índice: {series_prod.index}')

print(f'\nValores: {series_prod.values}')

print(f'\nEjes: {series_prod.axes}')

print(f'\nElementos: {series_prod.items}')

series_prod.name = 'Producción de la semana'

print(f'\nNombre: {series_prod.name}')

print(f'\nForma: {series_prod.shape}')

Índice: Index(['Dia 1', 'Dia 2', 'Dia 3', 'Dia 4', 'Dia 5'], dtype='str')

Valores: [1000 2100 1500 1300 9000]

Ejes: [Index(['Dia 1', 'Dia 2', 'Dia 3', 'Dia 4', 'Dia 5'], dtype='str')]

Elementos: <bound method Series.items of Dia 1    1000
Dia 2    2100
Dia 3    1500
Dia 4    1300
Dia 5    9000
dtype: int64>

Nombre: Producción de la semana

Forma: (5,)

In [13]:
# Ejemplo con la serie de producción

# Imprimir la serie de producción
print('\nSerie producción: ')
print(series_prod)

# Acceder a un elemento de la serie por su índice
print(series_prod['Dia 1'])

# modificar un elemento de la serie por su índice
series_prod['Dia 1'] += 500

# Imprimir la serie de producción modificada
print(series_prod)

# Filtrar elementos de la serie que sean mayores a 1500
print(series_prod[series_prod > 1500])

Serie producción:
Dia 1    1000
Dia 2    2100
Dia 3    1500
Dia 4    1300
Dia 5    9000
Name: Producción de la semana, dtype: int64
1000
Dia 1    1500
Dia 2    2100
Dia 3    1500
Dia 4    1300
Dia 5    9000
Name: Producción de la semana, dtype: int64
Dia 2    2100
Dia 5    9000
Name: Producción de la semana, dtype: int64

---
Recorrer una serie

In [14]:
# Creamos una serie de ejemplo
valores = pd.Series([10, 20, 30, 35, 40, 30], index=['a', 'b', 'c', 'd', 'e', 'f'])

# Imprimir la serie
print(valores)

# Imprimir los índices y valores de la serie que sean iguales a 30
print('\nElementos iguales a 30:')
for indice, valor in valores.items():
    if valor == 30:
        print(f'Índice: {indice}, Valor: {valor}')

a    10
b    20
c    30
d    35
e    40
f    30
dtype: int64

Elementos iguales a 30:
Índice: c, Valor: 30
Índice: f, Valor: 30

---
Data Frame

In [15]:
# Data frame
data = {
    'Nombre': ['Juan', 'Pedro', 'Maria', 'Ana'],
    'Edad': [25, 30, 28, 22],
    'Ciudad': ['Madrid', 'Barcelona', 'Valencia', 'Sevilla']
}

dataframe = pd.DataFrame(data)
print(dataframe)

  Nombre  Edad     Ciudad
0   Juan    25     Madrid
1  Pedro    30  Barcelona
2  Maria    28   Valencia
3    Ana    22    Sevilla

In [16]:
# Data frame con índices personalizados
dataframe = pd.DataFrame(data, index=['Persona 1', 'Persona 2', 'Persona 3', 'Persona 4'])
print(dataframe)

          Nombre  Edad     Ciudad
Persona 1   Juan    25     Madrid
Persona 2  Pedro    30  Barcelona
Persona 3  Maria    28   Valencia
Persona 4    Ana    22    Sevilla

In [17]:
dataframe = pd.DataFrame(data, index=['Persona 1', 'Persona 2', 'Persona 3', 'Persona 4'])
# Acceder a una columna del data frame por su índice
print(dataframe.loc['Persona 1'])

# Acceder a una columna del data frame por su posición
print(dataframe.iloc[1])

Nombre      Juan
Edad          25
Ciudad    Madrid
Name: Persona 1, dtype: object
Nombre        Pedro
Edad             30
Ciudad    Barcelona
Name: Persona 2, dtype: object

In [18]:
# Acceder a un elemento específico del data frame por su posición en los índices y columnas
print(dataframe.iloc[0, 1])

# Acceder a un elemento específico del data frame por su índice y columna
print(dataframe.loc['Persona 1', 'Nombre'])

25
Juan

In [19]:
# Modificar un elemento del data frame

# modificar los indices de la serie por otros personalizados
df_empleados = pd.DataFrame(data, index=['Empleado 1', 'Empleado 2', 'Empleado 3', 'Empleado 4'])
print('\n',df_empleados)

# Insertar una nueva columna en el data frame
df_empleados['Departamento'] = ['Ventas', 'IT', 'RRHH', 'Marketing']
print('\nCon nueva columna:\n', df_empleados)

# Agregar un nuevo registro al data frame
df_empleados.loc['Empleado 5'] = ['Carlos', 35, 'Bilbao', 'Finanzas']
print('\nCon nuevo registro:\n', df_empleados)

            Nombre  Edad     Ciudad
Empleado 1   Juan    25     Madrid
Empleado 2  Pedro    30  Barcelona
Empleado 3  Maria    28   Valencia
Empleado 4    Ana    22    Sevilla

Con nueva columna:
            Nombre  Edad     Ciudad Departamento
Empleado 1   Juan    25     Madrid       Ventas
Empleado 2  Pedro    30  Barcelona           IT
Empleado 3  Maria    28   Valencia         RRHH
Empleado 4    Ana    22    Sevilla    Marketing

Con nuevo registro:
             Nombre  Edad     Ciudad Departamento
Empleado 1    Juan    25     Madrid       Ventas
Empleado 2   Pedro    30  Barcelona           IT
Empleado 3   Maria    28   Valencia         RRHH
Empleado 4     Ana    22    Sevilla    Marketing
Empleado 5  Carlos    35     Bilbao     Finanzas

In [20]:
# Atributos del data frame

print(f'Índices: {df_empleados.index}')

print(f'\nColumnas: {df_empleados.columns}')

print(f'\nEjes: {df_empleados.axes}')

print(f'\nForma: {df_empleados.shape}')

Índices: Index(['Empleado 1', 'Empleado 2', 'Empleado 3', 'Empleado 4', 'Empleado 5'], dtype='str')

Columnas: Index(['Nombre', 'Edad', 'Ciudad', 'Departamento'], dtype='str')

Ejes: [Index(['Empleado 1', 'Empleado 2', 'Empleado 3', 'Empleado 4', 'Empleado 5'], dtype='str'), Index(['Nombre', 'Edad', 'Ciudad', 'Departamento'], dtype='str')]

Forma: (5, 4)

---
Ejercicio. Lectura de datos desde un archivo csv, explorar datos y aplicar algunos filtros.

In [21]:
# Exportar datos de un archivo CSV

datos = pd.read_csv('pokemon.csv')

# Dataframe con los datos del archivo CSV
print(datos)

     N.º      Nombre      Tipo1     Tipo2  Altura   Peso  Legendario
0      1   Bulbasaur     Planta    Veneno     0.7    6.9         0.0
1      2     Ivysaur     Planta    Veneno     1.0   13.0         0.0
2      3    Venusaur     Planta    Veneno     2.0  100.0         0.0
3      4  Charmander      Fuego       NaN     0.6    8.5         0.0
4      5  Charmeleon      Fuego       NaN     1.1   19.0         0.0
..   ...         ...        ...       ...     ...    ...         ...
145  146     Moltres      Fuego   Volador     2.0   60.0         1.0
146  147     Dratini     Dragón       1.8     3.3    0.0         NaN
147  148   Dragonair     Dragón         4    16.5    0.0         NaN
148  149   Dragonite     Dragón   Volador     2.2  210.0         0.0
149  150      Mewtwo   Psíquico         2   122.0    1.0         NaN

[150 rows x 7 columns]

In [22]:
# Forma de los datos del data frame
datos.shape

(150, 7)

In [23]:
# Primeros registros del data frame
datos.head()

  N.º      Nombre   Tipo1   Tipo2  Altura   Peso  Legendario
0   1   Bulbasaur  Planta  Veneno     0.7    6.9         0.0
1   2     Ivysaur  Planta  Veneno     1.0   13.0         0.0
2   3    Venusaur  Planta  Veneno     2.0  100.0         0.0
3   4  Charmander   Fuego     NaN     0.6    8.5         0.0
4   5  Charmeleon   Fuego     NaN     1.1   19.0         0.0

In [24]:
# Ultimos registros del data frame
datos.tail()

     N.º      Nombre      Tipo1     Tipo2  Altura   Peso  Legendario
145  146     Moltres      Fuego   Volador     2.0   60.0         1.0
146  147     Dratini     Dragón       1.8     3.3    0.0         NaN
147  148   Dragonair     Dragón         4    16.5    0.0         NaN
148  149   Dragonite     Dragón   Volador     2.2  210.0         0.0
149  150      Mewtwo   Psíquico         2   122.0    1.0         NaN

In [25]:
# Muestra una muestra aleatoria de los registros del data frame
datos.sample(5)

     N.º      Nombre      Tipo1  Tipo2  Altura  Peso  Legendario
116  117      Seadra       Agua    NaN     1.2  25.0         0.0
81    82    Magneton  Eléctrico  Acero     1.0  60.0         0.0
106  107  Hitmonchan      Lucha    NaN     1.4  50.2         0.0
38    39  Jigglypuff     Normal   Hada     0.5   5.5         0.0
7      8   Wartortle       Agua    NaN     1.0  22.5         0.0

In [26]:
# Describe estadisticamente los datos del data frame
datos.describe()

           Altura        Peso  Legendario
count  150.000000  150.000000  144.000000
mean     2.423333   44.949333    0.020833
std     10.310791   59.611774    0.143325
min      0.200000    0.000000    0.000000
25%      0.700000    9.000000    0.000000
50%      1.100000   30.000000    0.000000
75%      1.500000   55.850000    0.000000
max    122.000000  460.000000    1.000000

In [27]:
# Mostrar información general del data frame
datos.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   N.º         150 non-null    str
 1   Nombre      150 non-null    str
 2   Tipo1       150 non-null    str
 3   Tipo2       72 non-null     str
 4   Altura      150 non-null    float64
 5   Peso        150 non-null    float64
 6   Legendario  144 non-null    float64
dtypes: float64(3), str(4)
memory usage: 8.3 KB

In [28]:
# Acceder a una columna del data frame por su índice
print(datos['Nombre'])

0       Bulbasaur
1         Ivysaur
2        Venusaur
3      Charmander
4      Charmeleon
          ...
145       Moltres
146       Dratini
147     Dragonair
148     Dragonite
149        Mewtwo
Name: Nombre, Length: 150, dtype: str

In [29]:
# Imprimir varias columnas del data frame
print(datos[['Nombre','Altura', 'Peso']])

         Nombre  Altura   Peso
0     Bulbasaur     0.7    6.9
1       Ivysaur     1.0   13.0
2      Venusaur     2.0  100.0
3    Charmander     0.6    8.5
4    Charmeleon     1.1   19.0
..          ...     ...    ...
145     Moltres     2.0   60.0
146     Dratini     3.3    0.0
147   Dragonair    16.5    0.0
148   Dragonite     2.2  210.0
149      Mewtwo   122.0    1.0

[150 rows x 3 columns]

In [30]:
# Acceder a un registro del data frame por su índice
print(datos.loc[0])

N.º                   1
Nombre        Bulbasaur
Tipo1            Planta
Tipo2            Veneno
Altura              0.7
Peso                6.9
Legendario          0.0
Name: 0, dtype: object

In [31]:
# Acceder a un elemento específico del data frame por su posición en los índices y columnas
datos2 = pd.read_csv('pokemon.csv', index_col='Nombre')
print(datos2)

# Acceder a un registro del data frame por su índice
print(datos2.loc['Bulbasaur'])

# Acceder a un elemento específico del data frame por su índice y columnas
print(datos2.loc['Bulbasaur', 'Tipo1'])

# Acceder a un elemento específico del data frame por su posicion
print(datos2.iloc[0, 1])

            N.º      Tipo1     Tipo2  Altura   Peso  Legendario
Nombre
Bulbasaur     1     Planta    Veneno     0.7    6.9         0.0
Ivysaur       2     Planta    Veneno     1.0   13.0         0.0
Venusaur      3     Planta    Veneno     2.0  100.0         0.0
Charmander    4      Fuego       NaN     0.6    8.5         0.0
Charmeleon    5      Fuego       NaN     1.1   19.0         0.0
...         ...        ...       ...     ...    ...         ...
 Moltres    146      Fuego   Volador     2.0   60.0         1.0
 Dratini    147     Dragón       1.8     3.3    0.0         NaN
 Dragonair  148     Dragón         4    16.5    0.0         NaN
 Dragonite  149     Dragón   Volador     2.2  210.0         0.0
 Mewtwo     150   Psíquico         2   122.0    1.0         NaN

[150 rows x 6 columns]
N.º                1
Tipo1         Planta
Tipo2         Veneno
Altura           0.7
Peso             6.9
Legendario       0.0
Name: Bulbasaur, dtype: object
Planta
Planta

In [41]:
# Acceder a un rango de registros y columnas del data frame
print(datos2.loc['Bulbasaur':'Charmander', ['Tipo1', 'Tipo2', 'Altura']])

# Buscar un pokemon por su nombre en el data frame y mostrar sus datos
pokemonB = input('Introduce nombre de un pokemon:')
try:
    print(datos2.loc[pokemonB])
except KeyError:
    print('Ese pokemon no se encontro.')

             Tipo1   Tipo2  Altura
Nombre
Bulbasaur   Planta  Veneno     0.7
Ivysaur     Planta  Veneno     1.0
Venusaur    Planta  Veneno     2.0
Charmander   Fuego     NaN     0.6
N.º                  25
Tipo1         Eléctrico
Tipo2               NaN
Altura              0.4
Peso                6.0
Legendario          0.0
Name: Pikachu, dtype: object

Ejercicios de filtrado

In [33]:
# Filtrar todos los pokemones que tengan una altura mayor a 2.0 metros
# Mostrar la lista de pokemones que cumplan con la condición y mencionar cuantos son
altos = datos[datos['Altura'] > 2.0]
print(altos[['Nombre', 'Altura']])
print(f'\nCantidad de pokemones con altura mayor a 2.0 m: {len(altos)}')

         Nombre  Altura
14        Bicho    29.5
18      Rattata     3.5
19     Raticate    18.5
23        Arbok     3.5
94         Onix     8.8
114  Kangaskhan     2.2
129    Gyarados     6.5
130      Lapras     2.5
142     Snorlax     2.1
146     Dratini     3.3
147   Dragonair    16.5
148   Dragonite     2.2
149      Mewtwo   122.0

Cantidad de pokemones con altura mayor a 2.0 m: 13

In [34]:
# Filtrar todos los pokemones que tengan un peso mayor a 100.0 kilogramos
# Mostrar la lista de pokemones que cumplan con la condición y mencionar cuantos son
pesados = datos[datos['Peso'] > 100.0]
print(pesados[['Nombre', 'Peso']])
print(f'\nCantidad de pokemones con peso mayor a 100.0 kg: {len(pesados)}')

         Nombre   Peso
58     Arcanine  155.0
67      Machamp  130.0
74     Graveler  105.0
75       G olem  300.0
86      Dewgong  120.0
90     Cloyster  132.5
94         Onix  210.0
102   Exeggutor  120.0
110     Rhyhorn  115.0
111      Rhydon  120.0
129    Gyarados  235.0
130      Lapras  220.0
142     Snorlax  460.0
148   Dragonite  210.0

Cantidad de pokemones con peso mayor a 100.0 kg: 14

In [35]:
# Filtrar todos los pokemones Legendarios
# Mostrar la lista de pokemones que cumplan con la condición y mencionar cuantos son
legendarios = datos[datos['Legendario'] == 1]
print(legendarios[['Nombre', 'Tipo1', 'Tipo2', 'Legendario']])
print(f'\nCantidad de pokemones legendarios: {len(legendarios)}')

        Nombre       Tipo1     Tipo2  Legendario
143   Articuno       Hielo   Volador         1.0
144     Zapdos   Eléctrico   Volador         1.0
145    Moltres       Fuego   Volador         1.0

Cantidad de pokemones legendarios: 3

In [42]:
# Filtrar todos los pokemones que sean de tipo1 Agua y Tipo2 Agua (Los operadores bit a bit son: & (and), | (or), ~ (not))
# Mostrar la lista de pokemones que cumplan con la condición y mencionar cuantos son
agua_agua = datos[(datos['Tipo1'] == 'Agua') & (datos['Tipo2'] == 'Agua')]
print(agua_agua[['Nombre', 'Tipo1', 'Tipo2']])
print(f'\nCantidad de pokemones Tipo1 Agua y Tipo2 Agua: {len(agua_agua)}')

Empty DataFrame
Columns: [Nombre, Tipo1, Tipo2]
Index: []

Cantidad de pokemones Tipo1 Agua y Tipo2 Agua: 0

In [43]:
# Filtrar todos los pokemones que sean de tipo1 Fuego y Tipo2 Volador
# Mostrar la lista de pokemones que cumplan con la condición y mencionar cuantos son
fuego_volador = datos[(datos['Tipo1'] == 'Fuego') & (datos['Tipo2'] == 'Volador')]
print(fuego_volador[['Nombre', 'Tipo1', 'Tipo2']])
print(f'\nCantidad de pokemones Tipo1 Fuego y Tipo2 Volador: {len(fuego_volador)}')

      Nombre  Tipo1    Tipo2
5  Charizard  Fuego  Volador

Cantidad de pokemones Tipo1 Fuego y Tipo2 Volador: 1